=== epos-eu/converter-service/common-util/src/test/resources/schemas/plugin-descriptor.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://epos_ip.tcs/plugin.descriptor",
  "title": "Plugin Descriptor structure",
  "description": "Describes the format for plugin descriptors",
  "definitions": {
  	"validation-structure": {
  		"type": "object",
  		"required": [ "schema-name", "schema-location-type", "schema-location" ],
  		"properties": {
  			"pointer-expression": { "type": "string" },
  			"format-type": { "enum": [ "xml", "json" ] },
  			"schema-name": { "type": "string" },
  			"schema-location-type": { "enum": [ "path", "url" ] },
  			"schema-location": { "type": "string" },
  			"children": {
  				"type": "array",
  				"items": { "$ref": "#/definitions/child-validation-structure" }
  			}
  		},
  		"additionalProperties": false
  	},
  	"child-validation-structure": {
  		"type": "object",
  		"required": [ "pointer-expression", "format-type", "schema-name", "schema-location-type", "schema-location" ],
  		"properties": {
  			"pointer-expression": { "type": "string" },
  			"format-type": { "enum": [ "xml", "json" ] },
  			"schema-name": { "type": "string" },
  			"schema-location-type": { "enum": [ "path", "url" ] },
  			"schema-location": { "type": "string" },
  			"children": { 
  				"type": "array",
  				"items": { "$ref": "#/definitions/child-validation-structure" } 
  			}
  		},
  		"additionalProperties": false
  	}
  },
  "type": "object",
  "required": [ "name", "version", "author", "execution", "conversions" ],
  "properties": {
	"name": { "type": "string" },
	"id": { "type": "string" },
  	"version": { "type": "string" },
  	"author": {
  		"type": "object",
  		"required": [ "contact" ],
  		"properties": {
  			"name": { "type": "string" },
  			"contact": { "type": "string" }
  		},
  		"additionalProperties": true
  	},
  	"execution": {
  		"type": "object",
  		"required": [ "invoker-type", "target-detail" ],
  		"properties": {
  			"invoker-type": { 
  				"enum": [ "Java-Reflection", "Java-RMI", "Java-JINI", "Python", "Go" ]
  			},
  			"target-detail": { 
  				"type": "string" 
  			}
  		},
  		"additionalProperties": false
  	},
  	"conversions": {
  		"type": "array",
  		"items": {
  			"type": "object",
  			"required": [ "request", "response" ],
  			"properties": {
	  			"request": {
	  				"type": "object",
	  				"required": [ "type", "content-type" ],
	  				"properties": {
	  					"type": { "type": "string" },
	  					"content-type": { "type": "string" },
	  					"validation": { "$ref": "#/definitions/validation-structure" }
	  				},
	  				"additionalProperties": false
	  			},
	  			"response": {
	  				"type": "object",
	  				"required": [ "content-type" ],
	  				"properties": {
	  					"content-type": { "type": "string" },
	  					"validation": { "$ref": "#/definitions/validation-structure" }
	  				},
	  				"additionalProperties": false
	  			}
	  		},
	  		"additionalProperties": false
  		}
  	}
  },
  "additionalProperties": false	
}

=== epos-eu/converter-service/common-util/src/test/resources/content_for_schema_testing/valid/plugin_descriptor_#03.json
{
	"name": "station-default",
	"id": "STN-WP10",
	"version": "1.0.0",
	"author": {
		"name": "patkftgs.ac.uk",
		"contact": "email@email.com"
	},
	"execution": {
		"invoker-type": "Java-Reflection",
		"target-detail": "java_plugins_dir;plugin-station-default-0.0.1.jar;org.epos.converter.plugin.visualisestation.VisualiseStationXMLCallablePlugin"
	},
	"conversions": [{
		"request": {
			"type": "tcs/station/fdsn",
			"content-type": "application/xml",
			"validation": {
				"pointer-expression": "/",
				"format-type": "xml",
				"schema-name": "fsdn-station-restricted-1.0.xsd",
				"schema-location-type": "path",
				"schema-location": "/schemas/request",
				"children": [{			
					"pointer-expression": "/my-root-element/some-element-with-json-in",
					"format-type": "json",
					"schema-name": "my-nested.json",
					"schema-location-type": "path",
					"schema-location": "/schemas/request",
					"children": [{
						"pointer-expression": "$.some-xml-here",
						"format-type": "xml",
						"schema-name": "my-nested-nested.xml",
						"schema-location-type": "path",
						"schema-location": "/schemas/request"
					}]						
				},{
					"pointer-expression": "/my-root-element/some-element-with-xml-in",
					"format-type": "xml",
					"schema-name": "my-nested.xml",
					"schema-location-type": "path",
					"schema-location": "/schemas/request"
				}]
			}
		},
		"response": {
			"content-type": "application/epos.geo+json",
			"validation": {
				"schema-name": "geojson.json",
				"schema-location-type": "path",
				"schema-location": "/schemas/response"
			}
		}
	},{
		"request" : {
			"type": "tcs/station/wp10",
			"content-type": "application/xml",
			"validation": {
				"schema-name": "wp10-station.json",
				"schema-location-type": "url",
				"schema-location": "http://schemalocation.com/incoming"
			}
		},
		"response": {
			"content-type": "application/epos.geo+json",
			"validation": {
				"schema-name": "geojson.json",
				"schema-location-type": "url",
				"schema-location": "http://schemalocation.com/outgoing"
			}
		}
	}]
}

=== epos-eu/converter-service/plugin-invoker-test/src/main/resources/plugin-descriptor.json
{
	"name": "plugin-invoker-test",
	"id": "PLT-PAA01",
	"version": "1.0.0",
	"author": {
		"name": "patkftgs.ac.uk",
		"contact": "email@email.com"
	},
	"execution": {
		"invoker-type": "Java-Reflection",
		"target-detail": "some-jar-location-here;plugin-keywords-0.0.1-SNAPSHOT.jar;org.epos.converter.plugin.invokertest.InvokerTestCallablePlugin"
	},
	"conversions": [{
		"request": {
			"type": "OTHER_TRANSFORMATION_TYPE-1",				
			"content-type": "application/json",			
			"validation": {								
				"schema-name": "my_nice_schema_in.json",		
				"schema-location-type": "path",						
				"schema-location": "schemas/payload_incoming"
			}
		},
		"response": {
			"content-type": "application/json",			
			"validation": {													
				"schema-name": "my_nice_schema_out.json",
				"schema-location-type": "path",
				"schema-location": "schemas/payload_outgoing"
			}
		}
	}]
}
