=== epos-eu/converter-service/common-api/src/main/resources/schema/plugin-descriptor-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://epos_ip.tcs/plugin.descriptor",
  "title": "Plugin Descriptor structure",
  "description": "Describes the format for plugin descriptors",
  "definitions": {
  	"validation-structure": {
  		"type": "object",
  		"required": [ "schema-name", "schema-location-type", "schema-location" ],
  		"properties": {
  			"pointer-expression": { "type": "string" },
  			"format-type": { "enum": [ "xml", "json" ] },
  			"schema-name": { "type": "string" },
  			"schema-location-type": { "enum": [ "path", "url" ] },
  			"schema-location": { "type": "string" },
  			"children": {
  				"type": "array",
  				"items": { "$ref": "#/definitions/child-validation-structure" }
  			}
  		},
  		"additionalProperties": false
  	},
  	"child-validation-structure": {
  		"type": "object",
  		"required": [ "pointer-expression", "format-type", "schema-name", "schema-location-type", "schema-location" ],
  		"properties": {
  			"pointer-expression": { "type": "string" },
  			"format-type": { "enum": [ "xml", "json" ] },
  			"schema-name": { "type": "string" },
  			"schema-location-type": { "enum": [ "path", "url" ] },
  			"schema-location": { "type": "string" },
  			"children": { 
  				"type": "array",
  				"items": { "$ref": "#/definitions/child-validation-structure" } 
  			}
  		},
  		"additionalProperties": false
  	}
  },
  "type": "object",
  "required": [ "id", "name", "version", "author", "conversions" ],
  "properties": {
	"name": { "type": "string" },
	"id": { "type": "string" },
  	"version": { "type": "string" },
  	"plugin-location": { "type": "string" },
  	"author": {
  		"type": "object",
  		"required": [ "contact" ],
  		"properties": {
  			"name": { "type": "string" },
  			"contact": { "type": "string" }
  		},
  		"additionalProperties": true
  	},
  	"conversions": {
  		"type": "array",
  		"items": {
  			"type": "object",
  			"required": [ "execution", "request", "response" ],
  			"properties": {
				"execution": {
					"type": "object",
					"required": [ "invoker-type", "target-detail" ],
					"properties": {
						"invoker-type": { 
							"enum": [ "Java-Reflection", "Java-RMI", "Java-JINI", "Python", "Go" ]
						},
						"plugin-install-location": { 
							"type": "string" 
						},
						"target-detail": { 
							"type": "string" 
						}
					},
					"additionalProperties": false
				},
	  			"request": {
	  				"type": "object",
	  				"required": [ "type", "content-type" ],
	  				"properties": {
	  					"type": { "type": "string" },
	  					"content-type": { "type": "string" },
	  					"validation": { "$ref": "#/definitions/validation-structure" }
	  				},
	  				"additionalProperties": false
	  			},
	  			"response": {
	  				"type": "object",
	  				"required": [ "content-type" ],
	  				"properties": {
	  					"content-type": { "type": "string" },
	  					"validation": { "$ref": "#/definitions/validation-structure" }
	  				},
	  				"additionalProperties": false
	  			}
	  		},
	  		"additionalProperties": false
  		}
  	}
  },
  "additionalProperties": false	
}

=== epos-eu/converter-service/common-api/src/test/resources/sample_plugin_descriptors/valid/simple_#01.json
{
	"name": "station-default",
	"id": "STN-WP10",
	"version": "1.0.0",
	"author": {
		"name": "patkftgs.ac.uk",
		"contact": "email@email.com"
	},
	"conversions": [{
		"execution": {
			"invoker-type": "Java-Reflection",
			"plugin-install-location": "/plugins/java",
			"target-detail": "artefact-relative-location;plugin-station-default-0.0.1.jar;org.epos.converter.plugin.visualisestation.VisualiseStationXMLCallablePlugin"
		},
		"request": {
			"type": "tcs/station/fdsn",				
			"content-type": "application/xml",			
			"validation": {								
				"schema-name": "fsdn-station-restricted-1.0.xsd",		
				"schema-location-type": "path",						
				"schema-location": "/schemas/request"
			}
		},
		"response": {
			"content-type": "application/epos.geo+json",			
			"validation": {													
				"schema-name": "geojson.json",
				"schema-location-type": "path",
				"schema-location": "/schemas/response"
			}
		}
	},{
		"execution": {
			"invoker-type": "Java-Reflection",
			"plugin-install-location": "/plugins/java",
			"target-detail": "artefact-relative-location;plugin-station-default-0.0.1.jar;org.epos.converter.plugin.visualisestation.VisualiseStationXMLCallablePlugin"
		},
		"request" : {
			"type": "tcs/station/wp10",
			"content-type": "application/json",
			"validation": {
				"schema-name": "wp10-station.json",
				"schema-location-type": "url",
				"schema-location": "http://schemalocation.com/incoming"
			}
		},
		"response": {
			"content-type": "application/epos.geo+json",
			"validation": {
				"schema-name": "geojson.json",
				"schema-location-type": "url",
				"schema-location": "http://schemalocation.com/outgoing"
			}
		}
	}]
}
